### ISSUE TITLE
if fontsUseGoogleApis=true the actual font may be configurable (no overriding needed)

### ISSUE THREAD

**Issue by it-gro** [it-gro/hugo-theme-w3css-basic#170]

**Comment by it-gro** [comment]
```toml
[params]
  fontsUseGoogleApis=true
```

```toml
[params.googleApiFonts]
  # only relevant if fontsUseGoogleApis=true
  # used in partials/head.fonts.googleapis.html

  # choose a google font family name for a generic name
  # generic names may be empty
  # default, if no key at all is given in params.googleApiFonts: Ubuntu + Ubuntu Mono

  # (default) Set: Ubuntu
  #monospace  = "Ubuntu Mono"
  #sans-serif = "Ubuntu"
  #serif      = ""
  #cursive    = ""

  # Set: Glegoo
  monospace  = ""
  sans-serif = ""
  serif      = "Glegoo"
  cursive    = ""

  # Set: Days One
  #monospace  = ""
  #sans-serif = "Days One"
  #serif      = ""
  #cursive    = ""
```
