### ISSUE TITLE
Taxonomy pages don't render in debug mode

### ISSUE THREAD

**Issue by norristh** [it-gro/hugo-theme-w3css-basic#286]
I was using Hugo 0.36 with w3css-basic from January or so (I'm not sure where to find the exact version). When I just upgraded to Hugo 0.41 with the current w3css-basic, when I set debug to true in hugo, rendering the site generates the error:

> ERROR 2018/06/23 14:52:46 Error while rendering "taxonomy" in "": template: /home/user/sff/website/layouts/_default/taxonomy.html:34:13: executing "main" at <partial `main.teaser...>: error calling partial: template: partials/main.teaser_in_card.html:6:5: executing "partials/main.teaser_in_card.html" at <partial `main.teaser...>: error calling partial: template: theme/partials/main.teaserpic.card.html:12:3: executing "theme/partials/main.teaserpic.card.html" at <partial `resource.im...>: error calling partial: template: theme/partials/resource.image.html:28:46: executing "theme/partials/resource.image.html" at <$myGlobalResourcePag...>: can't evaluate field File in type *hugolib.Page

The problem seems to be the code block at line 26:
```
{{- if or $thePage.Site.Params.debug (findRE `\bdebug-partial(s|-resource-image)\b` ($thePage.Site.Param `traceFlags`) ) }}
  <br/>
  myGlobalResources: {{- $myGlobalResourcePage.File.Path }} <br/>
{{- end }}
```

The field .File doesn't seem to exist. I don't understand Hugo well enough to know how to fix it, so I'm just submitting this issue.

**Comment by it-gro** [comment]
Thx for submitting this issue.
I'll have a look later on ...
(I'm still on 0.40.2 - but I'll update)

**Comment by it-gro** [comment]
You were right.
I changed to:
```
  $myGlobalResourcePagePath: {{- $myGlobalResourcePagePath }} <br/>
  {{- if $myGlobalResourcePage }}
  myGlobalResources: {{- $myGlobalResourcePage.File.Path }} <br/>
  {{- end }}
```

You probably don't have a resources/images page (?).
See `exampleSite/content/resources/images/` for inspiration.

I added a new "default"  resource path handling via config.toml
`exampleSite/config.toml`
```toml
[params.resources]
	# used in layouts/partials/resource.image.html
	# used in layouts/shortcodes/res-figure.html
	# used in layouts/shortcodes/res-gallery.html
	defaultResPagePath	= "resources/images"

[params.resFigure]
	# used in layouts/shortcodes/res-figure.html
	defaultResPagePath	= "."			 
...
 
[params.resGallery]
	# used in layouts/shortcodes/res-gallery.html
	defaultResPagePath	= "resources/images" 
...
```
